# Generated by Django 5.1.1 on 2024-12-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_payment', models.IntegerField()),
                ('delay', models.IntegerField(default=0)),
                ('date_payment', models.DateField()),
                ('date_replenishment', models.DateField(null=True)),
                ('inn_legal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_user.legaluser')),
            ],
        ),
    ]
