# Generated by Django 5.1.1 on 2024-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type_product', models.CharField(max_length=50)),
                ('percent', models.FloatField()),
                ('repayment_period', models.IntegerField()),
                ('amount', models.FloatField()),
                ('recommended_payment', models.FloatField()),
            ],
        ),
    ]
