# Generated by Django 5.1.1 on 2024-12-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('credit_product', '0001_initial'),
        ('legal_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('credit_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_product.creditproduct')),
                ('email_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.administrator')),
                ('inn_legal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_user.legaluser')),
            ],
        ),
    ]
